/* Copyright (c) IGN - 2017 - tools
 *
 * Font definiton to use with fontsymbols
 */
ol.style.FontSymbol.addDefs
({
	"font": "tools",
	"name": "Tools",
	"copyright": "(c) IGN - 2017",
	"prefix": "tools"
},
{	"tools-arrow": {"font": "tools","code": 59396,"name": "arrow","search": "arrow"},
	"tools-color": {"font": "tools","code": 59397,"name": "color","search": "color"},
	"tools-copypoly": {"font": "tools","code": 59398,"name": "copypoly","search": "copypoly"},
	"tools-drawline": {"font": "tools","code": 59399,"name": "drawline","search": "drawline"},
	"tools-drawpoly": {"font": "tools","code": 59400,"name": "drawpoly","search": "drawpoly"},
	"tools-drawpoly-o": {"font": "tools","code": 59401,"theme": "drawpoly","name": "o","search": "drawpoly,o"},
	"tools-environnement-abeille": {"font": "tools","code": 59420,"theme": "environnement","name": "abeille","search": "environnement,abeille"},
	"tools-environnement-arbres": {"font": "tools","code": 59421,"theme": "environnement","name": "arbres","search": "environnement,arbres"},
	"tools-environnement-feuille": {"font": "tools","code": 59422,"theme": "environnement","name": "feuille","search": "environnement,feuille"},
	"tools-environnement-terre": {"font": "tools","code": 59423,"theme": "environnement","name": "terre","search": "environnement,terre"},
	"tools-help-larrow": {"font": "tools","code": 59416,"theme": "help","name": "larrow","search": "help,larrow"},
	"tools-help-rarrow": {"font": "tools","code": 59417,"theme": "help","name": "rarrow","search": "help,rarrow"},
	"tools-ign-map": {"font": "tools","code": 59424,"theme": "ign","name": "map","search": "ign,map"},
	"tools-ign-poi": {"font": "tools","code": 59438,"theme": "ign","name": "poi","search": "ign,poi"},
	"tools-ign-poi-o": {"font": "tools","code": 59439,"theme": "ign","name": "poi","search": "ign,poi-o"},
	"tools-ign-ville": {"font": "tools","code": 59426,"theme": "ign","name": "ville","search": "ign,ville"},
	"tools-ign-voiture": {"font": "tools","code": 59427,"theme": "ign","name": "voiture","search": "ign,voiture"},
	"tools-layer": {"font": "tools","code": 59402,"name": "layer","search": "layer"},
	"tools-layer2": {"font": "tools","code": 59403,"name": "layer2","search": "layer2"},
	"tools-layerdown": {"font": "tools","code": 59404,"name": "layerdown","search": "layerdown"},
	"tools-layers": {"font": "tools","code": 59405,"name": "layers","search": "layers"},
	"tools-layerstack": {"font": "tools","code": 59408,"name": "layerstack","search": "layerstack"},
	"tools-layerup": {"font": "tools","code": 59406,"name": "layerup","search": "layerup"},
	"tools-locate": {"font": "tools","code": 59407,"name": "locate","search": "locate"},
	"tools-logo-ign": {"font": "tools","code": 59437,"theme": "logo","name": "ign","search": "logo,ign"},
	"tools-logo-ign-seul": {"font": "tools","code": 59434,"theme": "logo","name": "ign","search": "logo,ign-seul"},
	"tools-logo-ign-vert": {"font": "tools","code": 59435,"theme": "logo","name": "ign","search": "logo,ign-vert"},
	"tools-logo-ign-vert-seul": {"font": "tools","code": 59436,"theme": "logo","name": "ign","search": "logo,ign-vert-seul"},
	"tools-loisir-chateau": {"font": "tools","code": 59428,"theme": "loisir","name": "chateau","search": "loisir,chateau"},
	"tools-loisir-marche": {"font": "tools","code": 59429,"theme": "loisir","name": "marche","search": "loisir,marche"},
	"tools-loisir-oeil": {"font": "tools","code": 59430,"theme": "loisir","name": "oeil","search": "loisir,oeil"},
	"tools-loisir-triomphe": {"font": "tools","code": 59431,"theme": "loisir","name": "triomphe","search": "loisir,triomphe"},
	"tools-measure": {"font": "tools","code": 59409,"name": "measure","search": "measure"},
	"tools-measure-line": {"font": "tools","code": 59410,"theme": "measure","name": "line","search": "measure,line"},
	"tools-measure-poly": {"font": "tools","code": 59411,"theme": "measure","name": "poly","search": "measure,poly"},
	"tools-measure-poly-o": {"font": "tools","code": 59412,"theme": "measure","name": "poly","search": "measure,poly-o"},
	"tools-modifyline": {"font": "tools","code": 59413,"name": "modifyline","search": "modifyline"},
	"tools-modifypoly": {"font": "tools","code": 59414,"name": "modifypoly","search": "modifypoly"},
	"tools-ol3": {"font": "tools","code": 59415,"name": "ol3","search": "ol3"},
	"tools-poi": {"font": "tools","code": 59392,"name": "poi","search": "poi"},
	"tools-recherche-carte": {"font": "tools","code": 59432,"theme": "recherche","name": "carte","search": "recherche,carte"},
	"tools-recherche-ecran": {"font": "tools","code": 59433,"theme": "recherche","name": "ecran","search": "recherche,ecran"},
	"tools-recherche-idee": {"font": "tools","code": 59418,"theme": "recherche","name": "idee","search": "recherche,idee"},
	"tools-recherche-poi": {"font": "tools","code": 59419,"theme": "recherche","name": "poi","search": "recherche,poi"},
	"tools-select": {"font": "tools","code": 59393,"name": "select","search": "select"},
	"tools-snap": {"font": "tools","code": 59394,"name": "snap","search": "snap"},
	"tools-vectorlayer": {"font": "tools","code": 59395,"name": "vectorlayer","search": "vectorlayer"}
});